### PR TITLE
Sync latest types

### PR DESCRIPTION
**Pull request by saboonikhil**

### CODE REVIEW

**Comment by saboonikhil** [comment]
Resolves #122

**Comment by saboonikhil** [comment]
@lsaether @sea212 @c410-f3r  

After making the required changes for market model, I am able to create market using `createCategoricalMarket` but getting error while decoding market received upon `system.ExtrinsicSuccess`. Same error is visible while using `viewDisputes` or `viewMarket`.

The error looks like below:
```
2021-09-28 21:30:48        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage marketCommons.markets:: createType(Market):: decodeU8a: failed at 0xc8153062220b0839… on period: {"_enum":{"Block":"(BlockNumber,BlockNumber)","Timestamp":"(Moment,Moment)"}}:: Unable to create Enum via index 200, in Block, Timestamp
Error: Unable to decode storage marketCommons.markets:: createType(Market):: decodeU8a: failed at 0xc8153062220b0839… on period: {"_enum":{"Block":"(BlockNumber,BlockNumber)","Timestamp":"(Moment,Moment)"}}:: Unable to create Enum via index 200, in Block, Timestamp
    at RpcCore._newType (/home/nikhil/Projects/tools/node_modules/@polkadot/rpc-core/bundle.cjs:450:13)
    at RpcCore._formatStorageData (/home/nikhil/Projects/tools/node_modules/@polkadot/rpc-core/bundle.cjs:399:17)
    at RpcCore._formatOutput (/home/nikhil/Projects/tools/node_modules/@polkadot/rpc-core/bundle.cjs:376:19)
    at callWithRegistry (/home/nikhil/Projects/tools/node_modules/@polkadot/rpc-core/bundle.cjs:255:42)
```

**Comment by c410-f3r** [comment]
On the latest type changes, `MarketPeriod` was changed from

```rust
pub enum MarketPeriod<BN> {
    Block((BN, BN)),
    Timestamp((u64, u64)),
}
```

to 

```rust
pub enum MarketPeriod<BN, M> {
    Block(Range<BN>),
    Timestamp(Range<M>),
}
```

Therefore, the TS type must also change to

```
"MarketPeriod": {
    "_enum": {
      "Block": "Range<BlockNumber>",
      "Timestamp": "Range<Moment>"
    }
  },
```

I am not saying that `types.json` isn't in sync but somewhere in this repository such change must be performed.

**Comment by saboonikhil** [comment]
Well yes, I have considered this change in my previous commits. The error is occuring at `@polkadot/rpc-core` when extracting raw from `api.query.marketCommons.markets(marketId)` before mapping it `Market` model in the SDK.

> On the latest type changes, `MarketPeriod` was changed from
> 
> ```rust
> pub enum MarketPeriod<BN> {
>     Block((BN, BN)),
>     Timestamp((u64, u64)),
> }
> ```
> 
> to
> 
> ```rust
> pub enum MarketPeriod<BN, M> {
>     Block(Range<BN>),
>     Timestamp(Range<M>),
> }
> ```
> 
> Therefore, the TS type must also change to
> 
> ```
> "MarketPeriod": {
>     "_enum": {
>       "Block": "Range<BlockNumber>",
>       "Timestamp": "Range<Moment>"
>     }
>   },
> ```
> 
> I am not saying that `types.json` isn't in sync but somewhere in this repository such change must be performed.

**Comment by saboonikhil** [comment]
@c410-f3r  

Well yes, I have considered this change in my previous commits. The error is occuring at @polkadot/rpc-core when extracting raw from api.query.marketCommons.markets(marketId) before mapping it Market model in the SDK.

**Comment by saboonikhil** [comment]
@c410-f3r 

Well yes, I have considered this change in my previous commits. The error is occuring at `@polkadot/rpc-core` while extracting raw from `api.query.marketCommons.markets(marketId)` before mapping it `Market` model in the SDK.

**Comment by lsaether** [comment]
@saboonikhil The error you posted would still imply that the old types are being loaded when the SDK is initialized. See the first line of the error message, specifically this part:

```
... {"_enum":{"Block":"(BlockNumber,BlockNumber)","Timestamp":"(Moment,Moment)"}}:: ...
```

Although I see in the [latest main branch](https://github.com/zeitgeistpm/tools/blob/main/packages/type-defs/src/predictionMarkets.ts#L29-L34) we've already merged in the change that @c410-f3r suggested for the type definitions.

Can you ensure the changes are pulled into the branch you are testing on (this one) and try again?

**Comment by c410-f3r** [comment]
`Range` is decoded and encoded as a tuple so `{"_enum":{"Block":"(BlockNumber,BlockNumber)","Timestamp":"(Moment,Moment)"}}` might already be the correct type, which suggests a divergent Zeitgeist node version as Logan said.

I tried to re-produce the issue but `market.test.ts` is using a non-existent `createNewMarket` method. Maybe it should be `createCategoricalMarket`?

**Comment by saboonikhil** [comment]
@c410-f3r Yes testing script needs to be updated. Meantime, could you please run the following command to reproduce the issue:

`yarn cli createCategoricalMarket "Test" "Test" "<oracle>" "2000 3000" "who will win?" --endpoint ws://127.0.0.1:9944`

**Comment by c410-f3r** [comment]
@saboonikhil Fields are de-serialized according to the declared order so can you re-order the `Market` object of `predictionMarkets.ts` to match https://github.com/zeitgeistpm/zeitgeist/blob/50ddcce28020476e26d28ab7bed43052d2ed7fa2/primitives/src/market.rs#L17-L41?

**Comment by lsaether** [comment]
Merged, @saboonikhil Can you try to make a release from the main branch using lerna?

Make sure you run `yarn compile` to make the latest built libs, then `lerna publish` should provide a prompt to walk you through it. This will be just a patch release.

**Pull request merged**
